// Seed suppliers for the RSS catalog. All entries are invented sample data:
// names are generic placeholders, phone numbers are deliberately fake, and
// `is_sample` is true so the admin app can flag them for replacement.

import type { Supplier } from '../types';

export const suppliers: Supplier[] = [
  // ── Dhaka: nurseries ────────────────────────────────────────────────
  {
    id: 'sup-dhk-nursery-1',
    name: 'Green Leaf Nursery (Sample)',
    kind: 'nursery',
    city: 'dhaka',
    area: 'Agargaon',
    contact_name: 'Sample Contact – Rahim',
    phone: '+880 1700-000-001',
    lead_time_days: 2,
    reliability_score: 88,
    payment_terms: 'Cash on delivery',
    is_sample: true,
  },
  {
    id: 'sup-dhk-nursery-2',
    name: 'Blossom Plant House (Sample)',
    kind: 'nursery',
    city: 'dhaka',
    area: 'Mirpur',
    contact_name: 'Sample Contact – Salma',
    phone: '+880 1700-000-002',
    lead_time_days: 3,
    reliability_score: 81,
    payment_terms: '50% advance, 50% on delivery',
    is_sample: true,
  },
  {
    id: 'sup-dhk-nursery-3',
    name: 'Kitchen Garden Seedlings (Sample)',
    kind: 'nursery',
    city: 'dhaka',
    area: 'Uttara',
    contact_name: 'Sample Contact – Jamal',
    phone: '+880 1700-000-003',
    lead_time_days: 2,
    reliability_score: 84,
    payment_terms: 'Weekly settlement (bKash)',
    is_sample: true,
  },
  {
    id: 'sup-dhk-nursery-4',
    name: 'Tropical Foliage Depot (Sample)',
    kind: 'nursery',
    city: 'dhaka',
    area: 'Mohammadpur',
    contact_name: 'Sample Contact – Nasrin',
    phone: '+880 1700-000-004',
    lead_time_days: 4,
    reliability_score: 76,
    payment_terms: 'Net 15 days',
    is_sample: true,
  },

  // ── Dhaka: pots ─────────────────────────────────────────────────────
  {
    id: 'sup-dhk-pots-1',
    name: 'Everyday Planters Supply (Sample)',
    kind: 'pots',
    city: 'dhaka',
    area: 'Mirpur',
    contact_name: 'Sample Contact – Habib',
    phone: '+880 1700-000-005',
    lead_time_days: 3,
    reliability_score: 86,
    payment_terms: 'Net 30 days',
    is_sample: true,
  },
  {
    id: 'sup-dhk-pots-2',
    name: 'Studio Ceramic & Stone Pots (Sample)',
    kind: 'pots',
    city: 'dhaka',
    area: 'Dhanmondi',
    contact_name: 'Sample Contact – Farhana',
    phone: '+880 1700-000-006',
    lead_time_days: 6,
    reliability_score: 79,
    payment_terms: '50% advance, 50% on delivery',
    is_sample: true,
  },

  // ── Dhaka: hardware ─────────────────────────────────────────────────
  {
    id: 'sup-dhk-hardware-1',
    name: 'Balcony Fittings & Hardware (Sample)',
    kind: 'hardware',
    city: 'dhaka',
    area: 'Gulshan',
    contact_name: 'Sample Contact – Tanvir',
    phone: '+880 1700-000-007',
    lead_time_days: 5,
    reliability_score: 83,
    payment_terms: 'Net 30 days',
    is_sample: true,
  },

  // ── Dhaka: accessories ──────────────────────────────────────────────
  {
    id: 'sup-dhk-accessories-1',
    name: 'Garden Essentials Store (Sample)',
    kind: 'accessories',
    city: 'dhaka',
    area: 'Agargaon',
    contact_name: 'Sample Contact – Mitu',
    phone: '+880 1700-000-008',
    lead_time_days: 2,
    reliability_score: 90,
    payment_terms: 'Net 15 days',
    is_sample: true,
  },

  // ── Chittagong: nurseries ───────────────────────────────────────────
  {
    id: 'sup-ctg-nursery-1',
    name: 'Hillside Green Nursery (Sample)',
    kind: 'nursery',
    city: 'chittagong',
    area: 'Nasirabad',
    contact_name: 'Sample Contact – Arif',
    phone: '+880 1700-000-009',
    lead_time_days: 3,
    reliability_score: 82,
    payment_terms: 'Cash on delivery',
    is_sample: true,
  },
  {
    id: 'sup-ctg-nursery-2',
    name: 'Coastal Bloom Nursery (Sample)',
    kind: 'nursery',
    city: 'chittagong',
    area: 'Khulshi',
    contact_name: 'Sample Contact – Rupa',
    phone: '+880 1700-000-010',
    lead_time_days: 4,
    reliability_score: 74,
    payment_terms: '50% advance, 50% on delivery',
    is_sample: true,
  },

  // ── Chittagong: pots ────────────────────────────────────────────────
  {
    id: 'sup-ctg-pots-1',
    name: 'Port City Clay Works (Sample)',
    kind: 'pots',
    city: 'chittagong',
    area: 'Agrabad',
    contact_name: 'Sample Contact – Sumon',
    phone: '+880 1700-000-011',
    lead_time_days: 5,
    reliability_score: 77,
    payment_terms: 'Net 15 days',
    is_sample: true,
  },

  // ── Chittagong: hardware & accessories ──────────────────────────────
  {
    id: 'sup-ctg-hardware-1',
    name: 'Port City Hardware & Garden Supplies (Sample)',
    kind: 'hardware',
    city: 'chittagong',
    area: 'GEC',
    contact_name: 'Sample Contact – Imran',
    phone: '+880 1700-000-012',
    lead_time_days: 4,
    reliability_score: 80,
    payment_terms: 'Net 30 days',
    is_sample: true,
  },
];
