// Generates supabase/seed/catalog.sql from the typed catalog in
// packages/core/src/catalog, so the app's demo mode and the real database
// always start from the same data. Run with `npm run db:seed`.

import { writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { bundles, products, suppliers } from '../../packages/core/src/catalog/index.ts';

const out = join(dirname(fileURLToPath(import.meta.url)), '..', '..', 'supabase', 'seed', 'catalog.sql');

const str = (v: string | null | undefined) => (v == null ? 'null' : `'${v.replace(/'/g, "''")}'`);
const num = (v: number) => (Number.isFinite(v) ? String(v) : 'null');
const bool = (v: boolean) => (v ? 'true' : 'false');
const json = (v: unknown) => (v == null ? 'null' : `${str(JSON.stringify(v))}::jsonb`);
const textArray = (v: string[]) => `array[${v.map(str).join(', ')}]::text[]`;

function upsert(table: string, columns: string[], rows: string[][], key: string): string {
  const updates = columns.filter((c) => c !== key).map((c) => `${c} = excluded.${c}`).join(', ');
  return [
    `insert into public.${table} (${columns.join(', ')}) values`,
    rows.map((r) => `  (${r.join(', ')})`).join(',\n'),
    `on conflict (${key}) do update set ${updates};`,
  ].join('\n');
}

const sql = [
  '-- Generated by tools/db/generate-seed.mts from packages/core/src/catalog. Do not edit by hand.',
  '',
  upsert(
    'suppliers',
    ['id', 'name', 'kind', 'city', 'area', 'contact_name', 'phone', 'lead_time_days', 'reliability_score', 'payment_terms', 'is_sample'],
    suppliers.map((s) => [
      str(s.id), str(s.name), str(s.kind), str(s.city), str(s.area), str(s.contact_name), str(s.phone),
      num(s.lead_time_days), num(s.reliability_score), str(s.payment_terms), bool(s.is_sample),
    ]),
    'id',
  ),
  '',
  upsert(
    'products',
    ['id', 'sku', 'category', 'name_en', 'name_bn', 'description_en', 'description_bn', 'price', 'stock', 'unit',
      'weight_kg', 'care_level', 'aesthetic_tags', 'supplier_id', 'illustration', 'image_url', 'active', 'plant', 'pot', 'hardware'],
    products.map((p) => [
      str(p.id), str(p.sku), str(p.category), str(p.name.en), str(p.name.bn), str(p.description.en), str(p.description.bn),
      num(p.price), num(p.stock), str(p.unit), num(p.weight_kg), str(p.care_level), textArray(p.aesthetic_tags),
      str(p.supplier_id), json(p.illustration), str(p.image_url ?? null), bool(p.active),
      json(p.plant ?? null), json(p.pot ?? null), json(p.hardware ?? null),
    ]),
    'id',
  ),
  '',
  upsert('product_costs', ['product_id', 'cost'], products.map((p) => [str(p.id), num(p.cost)]), 'product_id'),
  '',
  upsert(
    'bundles',
    ['id', 'slug', 'name_en', 'name_bn', 'description_en', 'description_bn', 'discount_pct', 'min_sun_hours', 'max_sun_hours', 'illustration'],
    bundles.map((b) => [
      str(b.id), str(b.slug), str(b.name.en), str(b.name.bn), str(b.description.en), str(b.description.bn),
      num(b.discount_pct), num(b.min_sun_hours), num(b.max_sun_hours), json(b.illustration),
    ]),
    'id',
  ),
  '',
  `delete from public.bundle_items where bundle_id in (${bundles.map((b) => str(b.id)).join(', ')});`,
  [
    'insert into public.bundle_items (bundle_id, product_id, quantity) values',
    bundles.flatMap((b) => b.items.map((i) => `  (${str(b.id)}, ${str(i.product_id)}, ${num(i.quantity)})`)).join(',\n') + ';',
  ].join('\n'),
  '',
].join('\n');

writeFileSync(out, sql);
console.log(`Wrote ${out}: ${suppliers.length} suppliers, ${products.length} products, ${bundles.length} bundles`);
